### ISSUE TITLE
How to prepare the dataset? like coco or imagenet

### ISSUE THREAD

**Issue by qifeng22** [wangck20/V2M#3]
Thanks for your excellent work. How to prepare the dataset for training the model？

**Comment by qifeng22** [comment]
@wangck20

**Comment by wangck20** [comment]
The construction of the dataset is consistent with other methods. For example, the ImageNet-1K dataset is obtained from the official website and contains three folders: meta, train, and val. The train and val folders contain training and validation samples, respectively, while the meta folder includes basic information about the samples.
